version: "3"            # optional but recommended
services:           
  resource-monitor:                             # service name
    build: .                                    # current directory for Dockerfile
    container_name: resource-monitor-container  # container name
    restart: always                             # restart policy, ensure the container is always running
    volumes:                                    # mount the docker socket to the container
      - /var/run/docker.sock:/var/run/docker.sock 

# The volume mount (optional) allows the container to interact with the Docker daemon of the host machine (e.g., for monitoring other containers).